const menu = [
    {
        id: 1,
        title: 'aglio olio',
        category: 'italian',
        price: 200,
        img: './images/aglio-olio.jpg',
    },
    {
        id: 2,
        title: 'alfredo pasta',
        category:'italian',
        price: 225,
        img:'./images/alfredo-pasta-white.jpg',
    },
     {
        id: 3,
        title: 'black jamun',
        category: 'desserts',
        price: 15,
        img:'./images/black-jamun.jpg',
    },
     {
        id: 4,
        title: 'brownies',
        category: 'desserts',
        price: 50,
        img:'./images/brownies.jpg',
    },
     {
        id: 5,
        title: 'burger',
        category: 'indian',
        price: 60,
        img:'./images/burger.jpg',
    },
     {
        id: 6,
        title: 'slice cake',
        category: 'desserts',
        price: 40,
        img:'./images/cake.jpg',
    },
     {
        id: 7,
        title: 'chai',
        category: 'beverages',
        price: 15,
        img:'./images/chai.jpg',
    },
     {
        id: 8,
        title: 'coffee',
        category: 'beverages',
        price: 40,
        img:'./images/coffee.jpg',
    },
     {
        id: 9,
        title: 'Special Coffee',
        category: 'beverages',
        price: 75,
        img:'./images/coffee2.jpg',
    },
     {
        id: 10,
        title: 'dosa',
        category: 'indian',
        price: 50,
        img:'./images/dosa.jpg',
    },
     {
        id: 11,
        title: 'gulab jamun',
        category: 'desserts',
        price: 20,
        img:'./images/gulab-jamun.jpg',
    },
     {
        id: 12,
        title: 'idli',
        category: 'indian',
        price: 40,
        img:'./images/idli.jpg',
    },
     {
        id: 13,
        title: 'jalebi',
        category: 'desserts',
        price: 35,
        img:'./images/jalebi.jpg',
    },
     {
        id: 14,
        title: 'kaju-katli',
        category: 'desserts',
        price: 100,
        img:'./images/kaju-katli.jpg',
    },
     {
        id: 15,
        title: 'lemon juice',
        category: 'beverages',
        price: 25,
        img:'./images/lemon-juice.jpg',
    },
     {
        id: 16,
        title: 'masala-chai',
        category: 'beverages',
        price: 30,
        img:'./images/masala-chai.jpg',
    },
     {
        id: 17,
        title: 'misal pav',
        category: 'indian',
        price: 70,
        img:'./images/misal-pav1.jpg',
    },
     {
        id: 18,
        title: 'paav bhaji',
        category: 'indian',
        price: 100,
        img:'./images/paav-bhaji.jpg',
    },
     {
        id: 19,
        title: 'pani puri',
        category: 'indian',
        price: 50,
        img:'./images/pani-puri.jpg',
    },
     {
        id: 20,
        title: 'pasta-al-pesto',
        category: 'italian',
        price: 175,
        img:'./images/pasta-al-pesto1.jpg',
    },
     {
        id: 21,
        title: 'Special Pasta',
        category: 'italian',
        price: 275,
        img:'./images/pasta-tomato-basil.jpg',
    },
     {
        id: 22,
        title: 'pizza',
        category: 'italian',
        price: 300,
        img:'./images/pizza.jpg',
    },
     {
        id: 23,
        title: 'salad',
        category: 'indian',
        price: 35,
        img:'./images/salad.jpg',
    },
     {
        id: 24,
        title: 'samosa',
        category: 'indian',
        price: 25,
        img:'./images/samosa.jpg',
    },
     {
        id: 25,
        title: 'sandwich',
        category: 'indian',
        price: 45,
        img:'./images/sandwich.jpg',
    },
     {
        id: 26,
        title: 'spaghetti',
        category: 'italian',
        price: 150,
        img:'./images/spaghetti.jpg',
    },
    {
        id: 27,
        title:'watermelon juice',
        category: 'beverages',
        price: 25,
        img: './images/watermelon-juice.jpg',
    },
    {
        id: 28,
        title: 'ziti alla norma',
        category: 'italian',
        price: 300,
        img: './images/ziti-alla-norma.jpg',
    },
];

export default menu;